config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :games
  resources :players

  patch '/meetups/:meetup_id/players' => 'meetups#add_players', as: :add_meetup_player
  patch '/meetups/:meetup_id/players/:id/remove' => 'meetups#remove_player', as: :remove_meetup_player

  resources :meetups do
    resources :players, only: [:index, :show]
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :meetup
  belongs_to :game
  has_and_belongs_to_many :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :events
  has_and_belongs_to_many :players

  def avg_rating
    avg = []
    self.events.each do |event|
      if !event.rating.nil?
        avg << event.rating
      end
    end
    if avg.length > 0
      avg = avg.inject(0){|r, e| r + e}.to_f / avg.length.to_f
      return avg.round(2)
    else
      return nil
    end
  end

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :events
  has_and_belongs_to_many :players

  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :meetups
  has_and_belongs_to_many :events
  has_and_belongs_to_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    redirect_to root_path
  end

  def new
    @meetup = Meetup.find(params[:meetup_id])
    @event = Event.new
    @url_path = meetup_events_path
  end

  def create
    event = Event.create(event_params[:event])
    event.meetup = Meetup.find(params[:meetup_id])
    event.save
    meetup = Meetup.find(params[:meetup_id])
    player_ids = params[:event][:players]
    player_ids.pop
    players = Player.find(player_ids)
    event.players << players
    redirect_to meetup_event_path(meetup_id: params[:meetup_id], id: event.id)
  end

  def edit
    @meetup = Meetup.find(params[:meetup_id])
    @event = Event.find(params[:id])
    @url_path = meetup_event_path(meetup_id: params[:meetup_id], id: params[:id])
  end

  def update
    event = Event.update(params[:id], event_params[:event])
    player_ids = params[:event][:players]
    player_ids.pop
    players = Player.find(player_ids)
    event.players = players
    redirect_to meetup_event_path(meetup_id: params[:meetup_id], id: params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.permit(event:[:game_id, :players, :duration, :outcome, :rating, :notes])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    Game.create(game_params[:game])
    redirect_to games_path
  end

  def show
    @game = Game.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    Game.update(params[:id], game_params[:game])
    redirect_to games_path
  end

  def destroy
    Game.destroy(params[:id])
    redirect_to games_path
  end


  private

  def game_params
    params.permit(game:[:name, :genre, :description, :time_to_play, :min_players, :max_players])
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  def index
    @meetups = Meetup.all
  end

  def show
    @meetup = Meetup.find(params[:id])
    @players = @meetup.players

    @games = []

    @meetup.events.each do |event|
      @games.push(event.game)
    end

  end

  def new
    @meetup = Meetup.new
  end

  def create
    Meetup.create(meetup_params[:meetup])
    redirect_to meetups_path
  end

  def edit
    @meetup = Meetup.find(params[:id])
  end

  def update
    Meetup.update(params[:id], meetup_params[:meetup])
    redirect_to meetups_path
  end

  def add_players
    meetup = Meetup.find(params[:meetup_id])
    player = Player.find(params[:meetup][:players])
    meetup.players << player
    redirect_to meetup_players_path
  end

  def remove_player
    meetup = Meetup.find(params[:meetup_id])
    player = Player.find(params[:id])
    meetup.players.delete(player)
    redirect_to meetup_path(meetup)
  end

  def destroy
    Meetup.destroy(params[:id])
    redirect_to meetups_path
  end

  private

  def meetup_params
    params.permit(meetup:[:name, :location, :date, :duration, :players])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index

    if request.path_info.include?('meetups')
      @meetup = Meetup.find(params[:meetup_id])
      @players = @meetup.players
      render :meetups_players_index
    else
      @players = Player.all
      render :index
    end

  end

  def new
    @player = Player.new
  end

  def create
    Player.create(player_params[:player])
    redirect_to players_path
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    Player.update(params[:id], player_params[:player])
    redirect_to players_path
  end

  def destroy
    Player.destroy(params[:id])
    redirect_to players_path
  end


  private

  def player_params
    params.permit(player:[:name, :email, :bio, :age, :city, :state])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event, url: @url_path, :html => { class: "form" } do |f| %>
  <div class="form-group">
    <%= f.label :game_id, "Game played: "%>
    <%= f.collection_select(:game_id, Game.all, :id, :name, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :players, "Add players from your meetup: "%>
    <%= f.collection_check_boxes :players, @meetup.players, :id, :name do |b| %>
      <div class="checkbox">
        <%= b.label do %>
          <%= b.check_box(class: "checkbox") %>
          <%= b.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :rating, "Rate this game on a scale of 1 (worst) to 10 (best) :"%>
        <%= f.number_field :rating, :min => 1, :max => 10, :step => 1, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :duration, "How long did it take? (hours) "%>
        <%= f.number_field :duration, :min => 0, :max => 8, :step => 0.5, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :outcome, "Describe the outcome of the game (e.g., who won?): "%>
    <%= f.text_area :outcome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :notes, "Other notes? "%>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <%= f.submit "#{button_text}", class: "btn btn-success" %>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <h1>Edit an event</h1>
</div>

<%= render partial: 'form', locals: { button_text: "Edit Event", method: :patch } %>

<%= link_to "Back to this event", meetup_event_path(meetup_id: params[:meetup_id], id: params[:id]), class: "btn btn-default footer" %>

app/views/events/new.html.erb
<div class="page-header">
  <h1>Enter a new event</h1>
</div>

<%= render partial: 'form', locals: { button_text: "New Event", method: :post } %>

<%= link_to "Back to the Meetup", meetup_path(params[:meetup_id]), class: "btn btn-default footer" %>

app/views/events/show.html.erb
<header id="title">
  <h1><%= @event.game.name %> at "<%= @event.meetup.name %>"</h1>
</header>

<%= link_to "Edit event info", edit_meetup_event_path(meetup_id: params[:meetup_id], id: params[:id]), class: "btn btn-info" %>
<%= link_to "Delete this event",  meetup_event_path(meetup_id: params[:meetup_id], id: params[:id]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
<%= link_to "Back to the Meetup", meetup_path(@event.meetup), class: "btn btn-default" %>

<div class="row">
  <div class="col-md-12">
    <h2>Event Info</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><strong>Players:</strong></td>
          <td>
            <% if @event.players.count > 1 %>
              <%= @event.players.pluck(:name).join(", ") %>
            <% else %>
              <em>none entered</em>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><strong>Duration:</strong></td>
          <td><% if @event.duration.present? %>
                <%= @event.duration %> hour<%= "s" if @event.duration != 1 %>
              <% else %>
                <em>none entered</em>
              <% end %>
           </td>
        </tr>
        <tr>
          <td><strong>Outcome:</strong></td>
          <td><% if @event.outcome.present? %>
                <%= @event.outcome %>
              <% else %>
                <em>none entered</em>
              <% end %>
           </td>
        </tr>
        <tr>
          <td><strong>Notes:</strong></td>
          <td><% if @event.notes.present? %>
                <%= @event.notes %>
              <% else %>
                <em>none entered</em>
              <% end %>
           </td>
        </tr>
        <tr>
          <td><strong>Rating:</strong></td>
          <td><% if @event.rating.present? %>
                <%= @event.rating %> out of 10
              <% else %>
                <em>none entered</em>
              <% end %>
           </td>
         </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/games/_form.html.erb
<%= form_for @game, :html => { :class => "form" } do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name: "%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :genre, "Genre: "%>
    <%= f.text_field :genre, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Description: " %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_to_play, "Time to play (hours): "%>
    <%= f.number_field :time_to_play, :min => 0, :step => 0.25, class: "form-control" %>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :min_players, "Number of players (minimum) :" %>
      <%= f.number_field :min_players, :min => 0, :step => 1, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :max_players, "Number of players (maximum) :" %>
      <%= f.number_field :max_players, :min => 0, :step => 1, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <%= f.submit "#{button_text}", class: "btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/games/edit.html.erb
<div class="page-header">
  <h1>Edit a game</h1>
</div>

<%= render partial: 'form', locals: { button_text: "Edit Game", method: :patch } %>

<%= link_to "Back to #{@game.name}", game_path(@game), class: "btn btn-default footer" %>

app/views/games/index.html.erb
<div class="page-header">
  <h1>Games</h1>
</div>

<%= link_to "Add a new game", new_game_path, class: "btn btn-success" %>

<h2>Click each game to see details or to edit/delete</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Players</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to "#{game.name}", game_path(game) %></td>
        <td><%= game.genre.capitalize %></td>
        <td><%= game.min_players %> to <%= game.max_players %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Back home", root_path, class: "btn btn-default" %>

app/views/games/new.html.erb
<div class="page-header">
  <h1>Enter a new game</h1>
</div>

<%= render partial: 'form', locals: { button_text: "New Game", method: :post } %>

<%= link_to "Back to Games", games_path, class: "btn btn-default footer" %>

app/views/games/show.html.erb
<div class="page-header">
  <h1><%= @game.name %></h1>
</div>

<%= link_to "Edit this game", edit_game_path(@game), class: "btn btn-info" %>
<%= link_to "Delete this game", game_path(@game), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<%= link_to "Back to Games", games_path, class: "btn btn-default" %>

<div class="row">
  <div class="col-md-12">
    <h2>Overview</h2>
    <p>
      <strong><%= @game.name %></strong> is a <%= @game.genre.downcase %> game
      for <%= @game.min_players %> to <%= @game.max_players %> players.
      This game takes approximately <%= @game.time_to_play %> hour<%= "s" if @game.time_to_play != 1 %> to play.
    </p>
    <% if @game.avg_rating != nil %>
      <h4>
        Average Rating: <%= @game.avg_rating %>
      </h4>
    <% elsif @game.avg_rating == nil %>
      <h4>
        This game's events are not yet rated.
      </h4>
    <% end %>
    <h2>Description</h2>
    <p>
      <%= simple_format @game.description %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Board Game Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Patrick+Hand|Nunito:400,300,700|Ruda:400,700,900|Capriola|Cabin|Titillium+Web|Dosis' rel='stylesheet' type='text/css'>
<div class="row">
  <div class="col-lg-12">
    <div class="jumbotron">
      <h1>My Board Game Diary!</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <%= link_to meetups_path, class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-flag" aria-hidden="true"></span> Meetups
    <% end %>
    <%= link_to players_path, class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Players
    <% end %>
    <%= link_to games_path, class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-knight" aria-hidden="true"></span> Games
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>
<body>
  <div class="container">
    <%= yield %>

  </div>
</body>
</html>

app/views/meetups/_form.html.erb
<%= form_for @meetup, :html => { :class => "form" } do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name: "%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <br>
    <%= f.label :location, "Location: "%>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date, "Date: "%>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <%= f.submit "#{button_text}", class: "btn btn-success" %>
<% end %>

app/views/meetups/edit.html.erb
<div class="page-header">
  <h1>Edit a meetup</h1>
</div>

<%= render partial: 'form', locals: { button_text: "Edit Meetup", method: :patch } %>

<%= link_to "Back to #{@meetup.name}", meetup_path(@meetup), class: "btn btn-default footer" %>

app/views/meetups/index.html.erb
<div class="page-header">
  <h1>Meetups</h1>
</div>

<%= link_to "Add a new meetup", new_meetup_path, class: "btn btn-success" %>

<h2>Click each meetup to see details, add/remove players and game events, or to edit/delete</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @meetups.each do |meetup| %>
      <tr>
        <td><%= link_to meetup.name, meetup_path(meetup) %></td>
        <td><%= meetup.location %></td>
        <td><%= meetup.date.strftime("%b %d, %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Back home", root_path, class: "btn btn-default" %>

app/views/meetups/new.html.erb
<div class="page-header">
  <h1>Enter a new meetup</h1>
</div>

<%= render partial: 'form', locals: { button_text: "New Meetup", method: :post } %>

<%= link_to "Back to Meetups", meetups_path, class: "btn btn-default footer" %>

app/views/meetups/show.html.erb
<div class="page-header">
  <h1>"<%= @meetup.name %>" on <%= @meetup.date.strftime("%b %d, %Y") %></h1>
</div>

<%= link_to "Edit meetup info", edit_meetup_path(@meetup), class: "btn btn-info" %>
<%= link_to "Delete this meetup", meetup_path(@meetup), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<%= link_to "Back to Meetups", meetups_path, class: "btn btn-default" %>

<div class="row">
  <div class="col-md-12">
    <h2>Step 1: <%= link_to "Add players to this meetup", meetup_players_path(params[:id]) %></h2>
      <% if @players.count > 0 %>
        <h3>Players at this meetup (so far!):</h3>
        <table class="table">
          <tbody>
            <% @players.each do |player| %>
              <tr>
                <td><%= player.name %> <%= link_to "(remove?)", remove_meetup_player_path(meetup_id: params[:id], id: player.id), method: :patch, :class => "remove_link" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Steps 2-100: <%= link_to "Add game events to this meetup", new_meetup_event_path(params[:id]) %> </h2>
    <% if @games.count > 0 %>
      <h3>Game events at this meetup (click for details or to edit/delete):</h3>
      <table class="table">
        <tbody>
          <% @meetup.events.each do |event| %>
            <tr>
              <td>
                <%= link_to event.game.name, meetup_event_path(meetup_id: params[:id], id: event.id), :class => "event_link" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => "form" } do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name: "%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Email: "%>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :city, "City: "%>
        <%= f.text_field :city, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :state, "State: "%>
        <%= f.select :state, ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"], {include_blank: true}, class: "form-control"  %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :age, "Age :" %>
        <%= f.number_field :age, :min => 13, :step => 1, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bio, "Bio: "%>
    <%= f.text_area :bio, class: "form-control" %>
  </div>
  <%= f.submit "#{button_text}", class: "btn btn-success" %>
<% end %>

app/views/players/edit.html.erb
<div class="page-header">
  <h1>Edit a player</h1>
</div>

<%= render partial: 'form', locals: { button_text: "Edit Player", method: :patch } %>

<%= link_to "Back to #{@player.name}", player_path(@player), class: "btn btn-default footer" %>

app/views/players/index.html.erb
<div class="page-header">
  <h1>Players</h1>
</div>

<%= link_to "Add a new player", new_player_path, class: "btn btn-success" %>

<h2>Click each player to see details or to edit/delete</h2>
  <table class="table table-hover">
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= link_to "#{player.name}", player_path(player) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to "Back home", root_path, class: "btn btn-default" %>

app/views/players/meetups_players_index.html.erb
<div class="page-header">
  <h1>Players for this meetup</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>So far, you have <%= @players.count %> player<%= "s" if @players.count != 1 %> at this meetup.</h2>
    <% if @players.count > 0 %>
      <table class="table">
        <tbody>
          <% @players.each do |player| %>
            <tr>
              <td><%= player.name %> <%= link_to "(remove?)", remove_meetup_player_path(meetup_id: params[:meetup_id], id: player.id), method: :patch %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Add a player</h2>
    <% if @meetup.players.count < Player.all.count %>
      <%= form_for @meetup, url: add_meetup_player_path(params[:meetup_id]), method: :patch, :html => { class: "form" } do |f| %>
        <div class="form-group">
          <%= f.label :players, "Player to add: "%>
          <%= f.collection_select(:players, Player.all.where.not(:id => @meetup.player_ids), :id, :name, class: "form-control") %>
        </div>
        <%= f.submit "Add Player", class: "btn btn-success" %>
      <% end %>
    <% else %>
      <strong>No more players to add!</strong> <%= link_to "Create one!", new_player_path, class: "btn btn-primary" %>
      </section>
    <% end %>
  </div>
</div>

<%= link_to "Back to #{@meetup.name}", meetup_path(@meetup), class: "btn btn-default footer" %>

app/views/players/new.html.erb
<div class="page-header">
  <h1>Enter a new player</h1>
</div>

<%= render partial: 'form', locals: { button_text: "New Player", method: :post } %>

<%= link_to "Back to Players", players_path, class: "btn btn-default footer" %>

app/views/players/show.html.erb
<div class="page-header">
  <h1><%= @player.name %></h1>
</div>

<%= link_to "Edit this player", edit_player_path(@player), class: "btn btn-info" %>
<%= link_to "Delete this player", player_path(@player), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
<%= link_to "Back to Players", players_path, class: "btn btn-default" %>

<div class="row">
  <div class="col-md-12">
    <h2>Overview</h2>
    <p>
      <strong><%= @player.name %></strong> is <%= @player.age %> years old.
      <%= @player.name %> lives in <%= @player.city %>, <%= @player.state %>.
    </p>

    <h2>Bio</h2>
    <p>
      <%= simple_format @player.bio %>
    </p>
  </div>
</div>